### ISSUE TITLE
Test failures due to hash randomisation in perl 5.17.6

### ISSUE THREAD

**Issue by andk** [monken/p5-moosex-attribute-deflator#4]
Since bleadperl v5.17.5-518-g7dc8663 your tests are failing frequently.
That commit introduced hash key randomization and it seems at least the test

t/structured.t

is hit by that. Find a sample fail report at:

http://www.cpantesters.org/cpan/report/a74b2e80-317b-11e2-a622-e9daa290f8f5

You can read more about the commit at
http://perl5.git.perl.org/perl.git/commit/7dc8663964c66a698d31bbdc8e8abed69bddeec3

You may have to run the test several times until the randomization causes a fail.

HTH&&Thanks&&Regards,

**Comment by monken** [comment]
has been fixed with 2.2.2
